
name: Entrega continua

on:
  workflow_call: #quando outra rotina chamar

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition Task-API-GO-Luiz --query taskDefinition > task-definition.json
