
name: Entrega continua

on:
  workflow_call: #quando outra rotina chamar

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
     - name: Configurando Credenciais AWS
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
     - name: Obtendo arquivo da tarefa
       run: aws ecs describe-task-definition --task-definition Task-API-GO-Luiz --query taskDefinition > task-definition.json

     - name: Fill in the new image ID in the Amazon ECS task definition
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
          task-definition: task-definition.json
          container-name: GO
          image: luiznascimentojr/go_ci:${{github.run_number}}
          environment-variables: |
             HOST=${{ secrets.DBHOST }}
             USER=${{ secrets.DBUSER }}
             PASSWORD=${{ secrets.DBPASSWORD }}
             DBNAME=${{ secrets.DBNAME }}
             DBPORT=${{ secrets.DBPORT }}
             PORT=8000 

     - name: Deploy Amazon ECS task definition
       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
       with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: Servico_API-Go
            cluster: API-Go
            wait-for-service-stability: true
